spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myproject?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: helloproject
    password: ww1234!!
    #url: jdbc:h2:tcp://localhost/~/test
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
  messages:
    basename: messages.messages, messages.errors, messages.validation
  #스프링 시큐리티 적용
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 91700057149-gbkmtcia2vea23clditi3ld26aor6d1h.apps.googleusercontent.com
            client-secret: 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
            scope:
              - name
              - email
              - profile


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        # show_sql: true
        format_sql: true
        user_sql_comments: true
        #지연 로딩 성능 최적화
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 방언 지정
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  #HTTP 요청 메시지를 서버에서 볼 수 있게 해줌
  org.apache.coyote.http11: trace

#쿠키 URL 전달방식 기능 off, 세션타임아웃 설정
server:
  port: 9090
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

file:
  profileImage:
    dir: C://study/Hello-World/file/user/profileImage/
  advice:
    dir: C://study/Hello-World/file/user/advice/
  board:
    dir: C://study/Hello-World/file/user/board/
  emp:
    dir: C://study/Hello-World/file/user/emp/


