spring:
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 91700057149-gbkmtcia2vea23clditi3ld26aor6d1h.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "https://www.hello-world.world/login/oauth2/code/google"
            scope:
              - email
              - profile