spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        # show_sql: true
 #       format_sql: true
#        user_sql_comments: true
        #지연 로딩 성능 최적화
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 방언 지정
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
    #HTTP 요청 메시지를 서버에서 볼 수 있게 해줌
#  org.apache.coyote.http11: trace